---
title: "MML - Review for Exam 2"
execute:
  echo: false
format:
  html:
    css: ../handout_style.css
    page-layout: article
    format-links: [pdf]
  pdf:
    mainfont: "Times New Roman"
    output-file: Exam2Review
    include-in-header:
      text: |
        \pagenumbering{gobble}
---

We will have our second exam next Friday, February 20. This review sheet is genuinely meant to help you succeed on that exam.

Generally, I will expect *solutions* to the problems, as opposed to just answers. So, for example, if the answer to an optimization problem is $y=5$, then the solution will consist of a clear explanation with correctly written supporting computations indicating *why* the answer is $y=5$.

::: {.content-visible when-format="html"}

Note that there is a link at the bottom of this sheet that will take you to a forum topic where you can ask questions about the sheet.

:::

## The problems

1. Write down definitions of the following:

   - [Linear transformation](https://marksmath.org/classes/Spring2026MML/presentations/Lecture05-LinearTransformations/#/the-importance-of-these-properties)
   - [Linear span of a set of vectors](https://marksmath.org/classes/Spring2026MML/presentations/Lecture07-Subspaces/#/linear-span)
   - [Linear independence of a set of vectors](https://marksmath.org/classes/Spring2026MML/presentations/Lecture07-Subspaces/#/linear-independence)
   - [Subspace of $\mathbb{R}^n$](https://marksmath.org/classes/Spring2026MML/presentations/Lecture07-Subspaces/#/subspaces)
   - [Basis of a subspace](https://marksmath.org/classes/Spring2026MML/presentations/Lecture07-Subspaces/#/spanning-sets-and-linear-independence)

2. A bit of data on NBA players is shown in @tbl-nba_players.

   a. What are the cases in the data table?
   b. Name one numerical variable.
   c. Name one nominal, categorical variable.
   d. Name one ordinal, categorical variable.

| first_name | last_name | team    | team_abbr | position        | number | height |
|-----------|------------|---------|------------|------------------|--------|--------|
| Alex      | Abrines    | Thunder | OKC        | Guard            | 8      | 78     |
| Jaylen    | Adams      | Hawks   | ATL        | Guard            | 10     | 74     |
| Steven    | Adams      | Thunder | OKC        | Center           | 12     | 84     |
| Bam       | Adebayo    | Heat    | MIA        | Center-Forward   | 13     | 82     |

: NBA Players {#tbl-nba_players}

3. Consider the numeric data $\{1, 1, 2, 4\}$.
   a. Write down the computation showing that the mean is $2$.
   b. Write down the computation showing that the standard deviation is $\sqrt{2}$.

4. Compute the determinants of the following matrices and use that information to determine the singularity or non-singularity of each matrix.

   a. 
$$
A = \begin{bmatrix}
  1 & 2 & 3 \\ 1 & 1 & 1 \\ 1 & -1 & 0
\end{bmatrix}
$$
   b. 
$$
B = \begin{bmatrix}
1 & 2 & 0 & 8 & -1 & 0 & 6 & 10 \\
2 & 0 & -8 & -1 & -1 & -1 & 1 & 1 \\
0 & 3 & 3 & 12 & 0 & -1 & 0 & 2 \\
1 & 10 & -6 & -25 & -1 & 0 & -1 & -4 \\
3 & 3 & -74 & 4 & 5 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 8 & 0 & -1 & 5 & 1 & 0 \\
4 & 0 & 1 & -4 & 0 & 1 & 0 & 1
\end{bmatrix}
$$
   c.
$$
C = \begin{bmatrix}
1 & 0 & -4 & 2 & 1 & -9 & 1 & 3 \\
0 & 1 & 2 & 1 & 0 & 0 & 17 & 0 \\
0 & 0 & 1 & -4 & 0 & 0 & -1 & -1 \\
0 & 0 & 0 & 1 & 0 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & -1 & -72 & 4 \\
0 & 0 & 0 & 0 & 0 & 1 & -4 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1
\end{bmatrix}
$$

5. Suppose that the matrix $A$ and its reduced row echelon form $R$ are
$$
A = \begin{bmatrix} 
1 & 2 & 3 & 4 \\ 
2 & 4 & 6 & 8 \\ 
3 & 5 & 7 & 9 
\end{bmatrix}
\quad 
R = \begin{bmatrix} 
1 & 0 & -1 & -2 \\ 
0 & 1 &  2 &  3 \\ 
0 & 0 &  0 &  0 
\end{bmatrix}
$$
   a. Provide a basis for the column space of $A$.
   b. Provide a basis for the null space of $A$.
   c. Provide a basis for the range of $A$.

6. Show that the null space of a linear transformation mapping $\mathbb R^n \to \mathbb R^m$ is closed under linear combinations and is, therefore, a subspace of $\mathbb R^n$.

\newpage

7. Let 
$$
A = \begin{bmatrix}1&2\\3&5\end{bmatrix}.
$$
   a. Row reduce the augmented matrix $[A|I]$.
   b. What is $A^{-1}$?

8. Suppose that $A$ is a non-singular matrix. Show that
$$(A^{-1})^{\mathsf{T}} = (A^{\mathsf{T}})^{-1}.$$


9. Find a value of $t$ such that
$$
\mathbf{x} = \begin{bmatrix}1 \\ 1 \\ -1 \\ 2t\end{bmatrix}
\quad \text{and} \quad 
\mathbf{y} = \begin{bmatrix}2 \\ 1 \\ 2 \\ 3\end{bmatrix}.
$$
are perpendicular.

10. Find the projection $\text{proj}_{\mathbf{b}}\mathbf{x}$ of the vector $\mathbf{x}$ onto $\mathbf{b}$, where 
$$
\mathbf{x} = \begin{bmatrix}1 \\ 0 \\ -1 \\ 2\end{bmatrix}
\quad \text{and} \quad 
\mathbf{b} = \begin{bmatrix}2 \\ 1 \\ 0 \\ 2\end{bmatrix}.
$$

11. Find the least squares solution to the overdetermined linear system
$$
\begin{bmatrix}
1&0\\0&-1\\1&1
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2
\end{bmatrix}
=
\begin{bmatrix}
1\\0\\1 
\end{bmatrix}.
$$


::: {.content-visible when-format="html"}

## Your questions and answers 

If you’d like to ask a question about or reply to a question on this sheet, you can do so by pressing the “Reply on Discourse” button below.

```{ojs}
embedDiscourseMathTopic(99)
```

```{ojs}
import {embedDiscourseMathTopic} from '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.js';
```

:::