project:
  title: "Observable in Discourse"
  type: website

format:
  revealjs:
    theme: default
    controls: true
    navigation-mode: vertical
    transition: slide
    progress: false
    history: false
    # multiplex: true
    css: styles.css
    html-math-method:
      method: mathjax
      url: "./tex-mml-svg.js"
    date-format: long
    template-partials:
      - title-slide.html
  beamer:
    aspectratio: 32
    navigation: vertical
    theme: default
    titlegraphic: "images/qrcode.pdf"
