---
title: Calculus I
css: styles.css
---

::: {.grid}
::::: {.g-col-12 .g-col-md-8}
Math 191  
Fall 2025  
with professor [Mark McClure](https://marksmath.org/)

## Handy links

- [Syllabus](syllabus.qmd)
- [Course Calendar](calendar.qmd)
- [APEX Calculus Textbook](https://opentext.uleth.ca/apex-calculus/apex-calculus.html){target=_blank}
- [MyOpenMath](https://myopenmath.com){target=_blank}
- [Discourse](https://discourse.marksmath.org){target=_blank}
- [The Math Lab!](https://math.unca.edu/learn/math-lab/){target=_blank}

## Handouts

- [Review for Quiz 1](handouts/ReviewForQuiz1/)
- [Review for Exam 1](handouts/ReviewForExam1/)
- [Review for Quiz 2](handouts/ReviewForQuiz2/)
- [Review for Exam 2](handouts/ReviewForExam2/)
- [Review for Quiz 3](handouts/ReviewForQuiz3/)
- [Review for Exam 3](handouts/ReviewForExam3/)
  - [ChatGPT tries Exam 3!](https://chatgpt.com/share/6923d34c-2568-8011-8e98-27b75e5391b4){target=_blank}
- [Final Review](handouts/FinalReview)

## Demos

- [Planetary motion](/visualization/class/orbits/)
- [A tricky limit](./demos/tricky_limit/)
- [IVT and the Bisection method](https://colab.research.google.com/drive/1qNeEvMcfw9AGXeuEarCJpp00v6jHz-lS?usp=sharing#forceEdit=true&sandboxMode=true){target=_blank}
- [Tangency and the derivative](/visualization/class/tangency/)
- [Grade flow](/visualization/data/grade_flow/)
- [Exponential slope](https://www.desmos.com/calculator/yffzmqda3s){target=_blank}
- Trigonometry
  - [Water waves](/visualization/class/water_waves/)
  - [The unit circle](/visualization/class/unit_circle)
  - [The graph of the sine](demos/sine_graph)
  - [Trig summation formulae](/visualization/class/trig_sums)
- Implicit graphs
  - [ Elliptic ](https://www.desmos.com/calculator/tftklsugfd){target=_blank}
  - [ Funky ](https://www.desmos.com/calculator/7jrocg30rs){target=_blank}
- [Inverses and derivatives](https://www.desmos.com/calculator/cnmoesr8fg){target=_blank}
- [Integration is hard!](/visualization/class/integration_is_hard)
- [Riemann Sums](/visualization/class/RiemannSums)

## Class Notes

- [Compound interest and $e$](notes/CompoundInterestAndE.qmd)
- [Linear regression](notes/linear_regression)
- [Newton's Method](notes/newtons_method)
- [Normal Probability](/writ/NormalProbability-Apr2025/)

:::::
::::: {.g-col-md-4 .d-none .d-md-block}
```{ojs}
import {side_pic} from './components/difference_quotient-side_pic.js'
side_pic();
```
:::::
:::
