---
title: Complex Variables
---

::: {.grid}
::::: {.g-col-12 .g-col-md-8}
Math 398 
Fall 2026  
with professor [Mark McClure](https://marksmath.org/)

## Handy links

- [Syllabus](syllabus.qmd)
- [Course Calendar](./calendar.qmd)
- [The Textbook](https://complexanalysis.org/web/root-1-2-2.html){target=_blank}
- [Writetech](https://math.writetech.ai){target=_blank}
- [Complex function visualizer](https://observablehq.com/d/fc69e46fd839132d){target=_blank}
- [The Math Lab!](https://www.unca.edu/math/math-lab/){target=_blank}

## Notes

- [Solving cubics with complex numbers](notes/ComplexCubics)
- [Visualizing complex images](notes/VisualizingComplexImages)
- Möbius transformations:
  - [Notes](notes/MobiusTransformations)
  - [Möbius transformations revealed](https://www.youtube.com/watch?v=0z1fIsUNhO4){target=_blank}
  - [Interactive](https://legacy.marksmath.org/visualization/mobius_revealed/){target=_blank}

## Handouts

- [Warmup Problems](handouts/WarmUp)
- [Solving a cubic](handouts/SolvingACubic)
- [Review for Quiz 1](handouts/ReviewForQuiz1/)
- [Review for Exam 1](handouts/ReviewForExam1/)


## Homework

Here's a [link to all your homework assignments on WriteTech AI](https://math.writetech.ai/c/complex-assignments). These are automatically graded assignments that provide instant AI feedback.

Alternatively, you can browse specific assignments via the following drop down menu:

```{ojs}
import { getCategoryAssignments } from "/components/GetDiscourseTags/GetDiscourseTags.js";
viewof assignment = {
    const assignments = await getCategoryAssignments("complex-assignments");
    let tag_objects = [{format: "---"}];
    tag_objects = tag_objects.concat(assignments.filter(function(assignment) {
        return typeof assignment === "string" || assignment?.tag;
    }).map(function(assignment) {
        const tag = typeof assignment === "string" ? assignment : assignment.tag;
        const n = tag.split("-").slice(-1)[0];
        const status = assignment.closed ? " Closed" :
            assignment.close ? ` closes ${assignment.close}` : "";
        const tFix = n == 1 ? "assignment-1" : tag;
        return ({format: `Assignment ${n}${status}`, value: tFix})
    }));
    return Inputs.select(tag_objects, {
        label: "View:", format: t => t.format
    })
}
```

::: {style="display: none"}
```{ojs}
{
    // React to assignment choice
    if(assignment.value) {
        window.open(`https://math.writetech.ai/tag/${assignment.value}`)
    }
}
```
:::

Note that you may need to allow popups for the dropdown menu to work and, in both cases, you'll need to be logged onto WriteTech to view your assignments.

:::::

::::: {.g-col-md-4 .d-none .d-md-block transform="translate(0,125px)"}
<div id='side_pic'></div>
:::::
:::

::: {style="display: none"}
```{ojs}
//| echo: false
import {interactiveFunPic} from './components/complexMark.js';
interactiveFunPic("side_pic")
```
:::
