---
title: Review for quiz 1
format:
  html:
    css: ['../handout_style.css', '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.css']
    page-layout: article
    format-links: [pdf]
  pdf:
    mainfont: "Times New Roman"
    output-file: Quiz1Review
    include-in-header:
      text: |
        \pagenumbering{gobble}
---

We have our first quiz next Friday, January 30. The quiz will have 3 or 4 problems which will look like a subset of the following problems.

If you have questions about any of the problems on this sheet, you can use the Reply on Discourse button down below.

## The problems

1. Let $S$ denote the sphere of radius $2$ centered at the point $(1,2,3)$.
   a. Find an equation of that sphere.
   b. I guess the intersection of $S$ with any plane should be either empty, a single point, or a circle. Which of those is it for each of the coordinate planes?

   *Note*: Spheres and the coordinate planes are covered in [sections 11.1.2 and 11.1.3](https://opentext.uleth.ca/apex-calculus/sec_space_coord.html#sec_space_coord-4){target=_blank} of our text.
2. Find a real number $t$ that makes the vector $\langle t+1,2t+1, 1-4t \rangle$ perpendicular to the vector $\langle 1,1,1 \rangle$.
3. Let $\vec{u} = \langle 4,1 \rangle$ and let $\vec{v} = \langle 1,2 \rangle$. 
   a. Draw the two vectors $\vec{u}$ and $vec{v}$ emanating from the same point, together with the vector $\text{proj}_{\vec{u}} \vec{v}$.
   b. Write down $\text{proj}_{\vec{u}} \vec{v}$ as a vector in terms of its components.

   *Note*: Orthogonal projection is defined in [Definition 11.3.14](https://opentext.uleth.ca/apex-calculus/sec_dot_product.html#def_orthogonal_projection){target=_blank} of our text.
4. Find an equation of the plane containing the three points $(1, 1, -1)$, $(1, 0, 0)$, and $(2, 3, 3)$.

   *Note*: [Example 11.6.3](https://opentext.uleth.ca/apex-calculus/sec_planes.html#ex_planes1){target=_blank} in our text is quite similar to this.
5. Write down a componentwise proof that the dot product is distributive over the addition of two-dimensional vectors - i.e.,
  $$
  \vec{u}\cdot(\vec{v} + \vec{w}) = \vec{u}\cdot\vec{v} + \vec{u}\cdot\vec{w},
  $$
  for all 2D vectors $\vec{u}$, $\vec{v}$, and $\vec{w}$.

   *Note*: A similar problem is [solved on our forum](https://discourse.marksmath.org/t/associativity-of-vector-addition/45){target=_blank}.

::: {.content-visible when-format="html"}

## Your questions and answers 

If you’d like to ask a question about or reply to a question on this sheet, you can do so by pressing the “Reply on Discourse” button below.

```{ojs}
embedDiscourseMathTopic(58)
```

```{ojs}
import {embedDiscourseMathTopic} from '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.js';
```

:::
