---
title: Class presentations
sidebar: MML2026
---

You can find the links to our daily class presentations below. Generally, I'll type these up in sufficient detail for the interested student to follow along. Of course, I didn't invent any of this and there are plenty of other references. Here are some other references for this material:

- [Open Intro Statistics](https://www.openintro.org/book/os/){target=blank} A free and open source introduction to elementary statistics
- [APEX Calculus](https://opentext.uleth.ca/apex-calculus/apex-calculus.html){target=_blank} A free, open source, and fairly standard Calculus textbook
- [A First Course in Linear Algebra](https://runestone.academy/ns/books/published/fcla/fcla.html){target=_blank} A free and open source text in Linear Algebra
- [Mathematics for Machine Learning](https://mml-book.github.io/){target=_blank} A text on the mathematics of machine learning made freely available by Cambridge University Press
- [The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/){target=_blank} A foundational text
- [An Introduction to Statistical Learning](https://www.statlearning.com/){target=_blank} A toned-down version of the previous text including code in R and Python

Of course, I learned most of this material many years ago and some of the presentations bear my own preferences. All mistakes are my own.

## Daily class presentations

- Mon, Jan 12: Intro and KNN
    - [Presentation](./Lecture00-Intro/){target=_blank}
    -
  <details>
    <summary>Comments</summary>
    <div>
      Today, we'll look at a couple groovy demos and jump right in to the K-Nearest Neighbor algorithm. We'll also get an overview of the course objectives and take a look at the syllabus.
    </div>
  </details>

- Wed, Jan 14: A quick review of Calc I
  - [Presentation](./Lecture01-CalcI/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    While Calc I is a requirement for this course, it's not a bad idea to refresh ourselves on some of the topics that we learn in that class. We'll do exactly that today, with a focus on derivatives and optimization.
  </div>
</details>

- Wed, Jan 16: An overview of Calc III
  - [Presentation](./Lecture02-CalcIII/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Today, we'll take a look at derivatives and optimization of multivariable functions, which is a small part of what's covered in Calculus III.
  </div>
</details>

- Wed, Jan 21: Linear systems and matrices
  - [Presentation](./Lecture03-SystemsAndMatrices/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Last time, we learned that optimization of multivariable functions leads naturally to systems of equations; when your function quadratic, the system is linear. Today, we'll recap that and push forward to studying linear systems in general.
  </div>
</details>

- Fri, Jan 23: Reduced row echelon form
  - [Presentation](./Lecture04-RREF/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Last time, we talked about linear systems and how they to the concept of a *matrix*. Today, we'll focus on matrices themselves and their reduced row echelon form.
  </div>
</details>

- Mon, Feb 2: Linear transformations and inverse matrices
  - [Presentation](./Lecture05-LinearTransformations/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    We've moved from systems of equations to their matrix representation. Now, we're going to focus on matrix multiplication and how it can be used to describe certain types of functions called *linear transformations*. A key step along the way is the construction of the inverse transformation.
  </div>
</details>

- Wed, Feb 4: Determinants
  - [Presentation](./Lecture06-Determinants/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Today we're going talk about the determinant: a single number that tells us how a linear transformation induced by a square matrix distorts the space on which it acts. Among other things, this gives us a simple test for singularity.
  </div>
</details>

- Fri, Feb 6: Subspaces
  - [Presentation](./Lecture07-Subspaces/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Today we'll talk about the concept of a subspace and show that the range of a linear transformation is a subspace that's equal to span of the columns of the corresponding matrix. Ultimately, we'll solve the corresponding linear regression problem by projecting onto the range.
  </div>
</details>

- Mon, Feb 9: Orthogonal projection via the dot product
  - [Presentation](./Lecture08-OrthogonalProjection/){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Today we'll introduce the dot project with a very important application - namely, orthogonal projection.
  </div>
</details>

- Wed, Feb 11: Intro to Data 
  - [Colab Notebook](https://colab.research.google.com/drive/1aVdSbkPg_-SC88i04-G_jNCSRIeLYfTO?usp=sharing#sandboxMode=true){target=_blank}
  -
<details>
  <summary>Comments</summary>
  <div>
    Today, we're going to take a look at a Colab Notebook that describes how we think about data and how to work with it using Python.
  </div>
</details>

- Fri, Feb 13: Linear regression theory and practice
  - [General examples](../notes/linear_regression_examples)
  - [Massey ratings](../notes/massey_ratings)
  -
<details>
  <summary>Comments</summary>
  <div>
    Today, we'll summarize general linear regression from the perspective of linear algebra and take a look at a bunch of examples.
  </div>
</details>

- Mon, Feb 16: Practical issues
  - [Presentation](./Lecture10-PracticalIssues){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Today, we'll take a look at some of the practical issues that arise when you attempt actual work with messy, real-world data. We'll do so in the context of a Kaggle competition that we'll try ourselves next week.
  </div>
</details>

- Mon, Feb 23: Integration
  - [Presentation](./Lecture11-Integration){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    We're going to shift gears today, step back into calculus and review integration. Our main application of integration will be to help us understand probability theory.
  </div>
</details>

- Wed, Feb 25: Lab 1 on Practical Regression
  - [Lab 1](https://colab.research.google.com/drive/1AD9QD6Ey89jSLZi8rjNmvyUKnpGwGBCm?usp=sharing#sandboxMode=true){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    We've got our first lab today on Practical Regression. We'll actually apply these ideas to a real world problem!
  </div>
</details>

- Friday, Feb 27: Numerical integration and probability
  - [Presentation](./Lecture12-NumericalIntegration){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
  Today, we're going to take an overview of where we are and start the transition into probability theory so that we can do some logistic regression.    
  </div>
</details>

- Mon, Mar 2: Discrete probability
  - [Presentation](./Lecture13-DiscreteProbability){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Recently, we reviewed the basics of integration and then we saw an overview of how that might be applied to probability theory. Today, we start probability theory in earnest with a discussion of discrete probability.
  </div>
</details>

- Wed, Mar 4: Continuous probability
  - [Presentation](./Lecture14-ContinuousProbability){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Last time, we started probability theory in earnest with a discussion of discrete probability. Today, we'll discuss continuous probability with an emphasis on the normal distribution.
  </div>
</details>

- Fri, Mar 6: Maximum likelihood and logistic Regression
  - [Presentation](./Lecture15-BasicLogistics){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    We've been working to get to this point where we can understand the basics of logistic regression and that's what we'll do today. We'll apply it when we get back together after Spring break.
  </div>
</details>

- Mon, Mar 16: Recap and practical logistics
  - [Presentation](./Lecture16-PracticalLogistics){target=_blank}
  - [The Titanic Notebook](https://colab.research.google.com/drive/13awlut4wVRnSfrHLLfh6SEDNqmocs3cP?usp=sharing#sandboxMode=true){target=_blank}
  - The NCAA Competition: 
    - [NCAA Brackets](/visualization/data/NCAABrackets/){target=_blank}
    - [Kaggle Brackets](/visualization/data/NCAABrackets/KaggleBrackets/){target=_blank}
    - [Kaggle's Competition](https://www.kaggle.com/competitions/march-machine-learning-mania-2026/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Seeing as how we just returned from Spring break, today we're going to take a moment to review some of the stuff we've learned before we jump into applying it in a practical setting.
  </div>
</details>

- Wed, Mar 18: Lab 2 - Logistic regression for Kaggle's NCAA bracket competition
  - [Kaggle's competition](https://www.kaggle.com/competitions/march-machine-learning-mania-2026/){target=_blank}
  - [Tournaments](https://observablehq.com/d/0c9a74558b7bae12){target=_blank}
  - [NCAA brackets](../../../visualization/data/NCAABrackets/){target=_blank}
  - [Kaggle prediction brackets](../../../visualization/data/NCAABrackets/KaggleBrackets/){target=_blank}
  - [The lab notebook](https://colab.research.google.com/drive/1vekA2CZksPkxWEm93-WE1xdDtxVbzGhN?usp=sharing#sandboxMode=true){target=_blank} 

- Fri, Mar 20: Eigenspaces
  - [Presentation](./Lecture17-Eigenspaces){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    We've pretty much finished up linear and logistic regression. Today, we'll discuss the very basics of eigenvalues and eigenvectors, which is the last stuff on our exam next week. We should also be sure to take a quick look at the [Review for Exam III](../handouts/Exam3Review)
  </div>
</details>

- Mon, Mar 23: Eigenrating
  - [Notes](../notes/eigenrating/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Now that we've learned about eigenvalues and eigenvectors, we're going to see our first data based application, namely *eigenrating*.

    While this material is again expressed in terms of the ranking of sports teams, it's worth mentioning that the same technique also has application of to networks. When we apply this basic idea to the world wide web, in fact, we get Google's Page Rank algorithm!
  </div>
</details>

- Mon, Mar 30: Diagonalization
  - [Presentation](./Lecture18-Diagonalization/){target=_blank}
  - [Notes on power iteration](../notes/power_iteration/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Today, we're going to discuss a major application of eigenvalues and eigenvectors, namely diagonalization of a matrix. This allows us to relate many matrices to a canonical form whose action is easier to understand. 
    
    Among other things, this yields an algorithm to compute the dominant eigenvector of a matrix.
  </div>
</details>

- Wed, Apr 1: Principal component Analysis
  - [Presentation](./Lecture19-PCA/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Today, we'll discuss principal component analysis (or PCA), which is a dimensional reduction technique that's a bit more advanced than simple variable selection.
  </div>
</details>

- Fri, Apr 3: Networks
  - [Presentation](./Lecture20-Networks/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Networks model pairwise relationships between discrete elements within a system. We've used them a little bit before but, today, we'll solidify our understanding of these important models so that we can use them in our study of Neural networks.
  </div>
</details>

- Mon, Apr 6: Expression Graphs
  - [Presentation](./Lecture21-ExpressionGraphs/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Last time, we learned a bit about networks and graph theory. We ended with abstract syntax trees, which provide a graph theoretic way to view algebraic expressions. Since trees can be manipulated as data structures, this yields a framework for us to perform algebra on the computer.

    Today, we're going to take a look at an alternative way to represent algebraic expressions as graphs - the so-called *expression graph*, also called a *computation graph*. This alternative is better suited for efficient numerical computation of values and derivatives.
  </div>
</details>

- Wed, Apr 8: Neural Networks
  - [Presentation](./Lecture22-NeuralNetworks/){target=_blank}
<details>
  <summary>Comments</summary>
  <div>
    Now that we've talked about both general networks and expression graphs, we're in a good spot to discuss neural networks. We'll focus today on the foundational *feed forward neural network* - how we represent it, how we compute with it, how we code it, how it's optimized, and what can do with it. We'll discuss variations on that foundational architecture a bit later.
  </div>
</details>