---
title: Linear Algebra
css: styles.css
---

::: {.grid}
::::: {.g-col-12 .g-col-md-8}
Math 365, Fall 2025  
with professor [Mark McClure](https://marksmath.org/)

## Handy links

- [Syllabus](syllabus.qmd)
- Course schedule 
  - [Outline](schedule/outline.qmd)
  - [Calendar](schedule/calendar.qmd)
- [The textbook](https://understandinglinearalgebra.org/ula.html){target=_blank}
- [MyOpenMath](https://myopenmath.com){target=_blank}
- [The Sage Cell Server](https://sagecell.sagemath.org/){target=_blank}
- [The Math Lab!](https://math.unca.edu/learn/math-lab/){target=_blank}

## Notes

- [Geometry of systems](notes/geometry_of_systems)
- [Reduced row echelon form](notes/some_row_reduction)
- [Using SageMath](notes/sage)
- [Componentwise proofs](notes/componentwise_proofs)
- [Geometry of linear transformations](notes/geometry_of_linear_transformations)
- [Determinants](notes/elementary_determinants)
- [Subspaces](notes/subspace_quiz_prep)
- [Eigenspaces](notes/eigenspaces)
- [Diagonalization](notes/diagonalization)
- Eigenratings
  - [Notes](notes/eigenratings)
  - [Colab notebook](https://colab.research.google.com/drive/1soQY6vIGJxofF6-AiQvF4dO0v9pfFOyX?usp=sharing#forceEdit=true&sandboxMode=true){target=_blank}
  - [Lab](eigenranking_project)
- [Cosine similarity](notes/CosineSimilarity)
- [Computing orthogonal projections](notes/orthogonal_projection)
- [Orthogonal least squares](notes/least_squares)
- [Massey Ratings](notes/MasseyRatings)
- Abstract vector spaces
  - [VS chapter in FCLA](https://runestone.academy/ns/books/published/fcla/chapter-VS.html){target=_blank}
  - [Inner products](notes/inner_products)
  - [A Legendre polynomial computation](https://sagecell.sagemath.org/?q=ggmlyp){target=_blank}

## Handouts

- [Problems for day 1](handouts/TypesOfSolutions2D-Day1.qmd) 
- [Review for Quiz 1](handouts/ReviewForQuiz1.qmd)
- [Review for Exam 1](handouts/ReviewForExam1.qmd)
- [Review for Quiz 2](handouts/ReviewForQuiz2.qmd)
- [Review for Exam 2](handouts/ReviewForExam2.qmd)
- [Review for Quiz 3](handouts/ReviewForQuiz3.qmd)
- [Final Review](handouts/FinalReview.qmd)

<!--  - [Chat GPT tries the quiz!](https://chatgpt.com/share/691dd96c-c9f8-8011-84ad-157b5c58329b){target=_blank} -->


:::::
::::: {.g-col-md-4 .d-none .d-md-block}
```{ojs}
import {eigen_pic} from './components/linear-side_pic.js'
eigen_pic(
    [
      [1, 1],
      [1/2, 3/2]
    ],
    [
      [1, 1],
      [-2, 1]
    ],
    { dd: 0.2 }
  )
```
:::::
:::
