---
title: Reduction to reduced row echelon form
date: 2025-08-20
format:
  html:
    toc: true
    css: styles.css
  pdf:
    toc: false
    mainfont: "Times New Roman"
    output-file: RowReduction
---

Here's a bit of info and examples on Reduced Row Echelon Form (RREF).

## The definition

We say that a matrix is in reduced row echelon form if the following properties are satisfied.

- If the entries in a row are all zero, then the same is true of any row below it.
- If we move across a row from left to right, the first nonzero entry we encounter is 1. We call this entry the leading entry in the row.
- The leading entry in any row is to the right of the leading entries in all the rows above it.
- A leading entry is the only nonzero entry in its column.

## Some RREF examples?? 

Which of these look like they are in reduced row echelon form?

$$
B_1=\begin{bmatrix}
1&0&2&0&0\\
0&1&-3&0&0\\
0&0&0&1&5\\
0&0&0&0&0
\end{bmatrix}
$$

$$
B_2=\begin{bmatrix}
1&0&2&0&0\\
0&0&0&0&0\\
0&1&-3&0&0\\
0&0&0&1&5
\end{bmatrix}
$$

$$
B_3=\begin{bmatrix}
1&2&0&0&1\\
0&1&0&0&-3\\
0&0&0&1&4\\
0&0&0&0&0
\end{bmatrix}
$$


## Performing row reduction

Here area few examples illustrating row reduction to reduced row echelon form.


### The typical situation

$$
\begin{aligned}
\left[
\begin{array}{rrr|r}
1&0&1&2\\
0&0&1&3\\
1&1&0&-1
\end{array}
\right]
&\xrightarrow{\;R_3\leftarrow R_3-R_1\;}
\left[
\begin{array}{rrr|r}
1&0&1&2\\
0&0&1&3\\
0&1&-1&-3
\end{array}
\right] \\[1.0em]
&\xrightarrow{\;R_2\leftrightarrow R_3\;}
\left[
\begin{array}{rrr|r}
1&0&1&2\\
0&1&-1&-3\\
0&0&1&3
\end{array}
\right] \\[1.0em]
&\xrightarrow{\;R_2\leftarrow R_2+R_3\;}
\left[
\begin{array}{rrr|r}
1&0&1&2\\
0&1&0&0\\
0&0&1&3
\end{array}
\right] \\[1.0em]
&\xrightarrow{\;R_1\leftarrow R_1-R_3\;}
\left[
\begin{array}{rrr|r}
1&0&0&-1\\
0&1&0&0\\
0&0&1&3
\end{array}
\right]
\end{aligned}
$$


### Infinitely many solutions

$$
\begin{aligned}
\left[
\begin{array}{rrr|r}
1&2&3&1\\
4&5&6&1\\
7&8&9&1
\end{array}
\right]
&\xrightarrow{\;R_2\leftarrow R_2-4R_1,\; R_3\leftarrow R_3-7R_1\;}
\left[
\begin{array}{rrr|r}
1&2&3&1\\
0&-3&-6&-3\\
0&-6&-12&-6
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_2\leftarrow -\tfrac{1}{3}R_2\;}
\left[
\begin{array}{rrr|r}
1&2&3&1\\
0&1&2&1\\
0&-6&-12&-6
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_3\leftarrow R_3+6R_2\;}
\left[
\begin{array}{rrr|r}
1&2&3&1\\
0&1&2&1\\
0&0&0&0
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_1\leftarrow R_1-2R_2\;}
\left[
\begin{array}{rrr|r}
1&0&-1&-1\\
0&1&2&1\\
0&0&0&0
\end{array}
\right]
\end{aligned}
$$

### An inconsistent system


$$
\begin{aligned}
\left[
\begin{array}{rrr|r}
1&4&5&7\\
2&8&10&14\\
3&12&15&22
\end{array}
\right]
&\xrightarrow{\;R_2\leftarrow R_2-2R_1,\; R_3\leftarrow R_3-3R_1\;}
\left[
\begin{array}{rrr|r}
1&4&5&7\\
0&0&0&0\\
0&0&0&1
\end{array}
\right] \\[1.0em]
&\xrightarrow{\;R_2\leftrightarrow R_3\;}
\left[
\begin{array}{rrr|r}
1&4&5&7\\
0&0&0&1\\
0&0&0&0
\end{array}
\right] \\[1.0em]
&\xrightarrow{\;R_1\leftarrow R_1-7R_2\;}
\left[
\begin{array}{rrr|r}
1&4&5&0\\
0&0&0&1\\
0&0&0&0
\end{array}
\right]
\end{aligned}
$$


### A randomly chosen system 

$$
\begin{aligned}
\left[
\begin{array}{rrr|r}
8 & 12 & 10 & 7\\
12 & 9 & 1 & 10\\
5 & 9 & 1 & 2
\end{array}
\right]
&\xrightarrow{\;R_1 \leftrightarrow R_2\;}
\left[
\begin{array}{rrr|r}
12 & 9 & 1 & 10\\
8 & 12 & 10 & 7\\
5 & 9 & 1 & 2
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_2\leftarrow R_2-\tfrac{2}{3}R_1,\; R_3\leftarrow R_3-\tfrac{5}{12}R_1\;}
\left[
\begin{array}{rrr|r}
12 & 9 & 1 & 10\\
0 & 6 & \tfrac{28}{3} & \tfrac{1}{3}\\
0 & \tfrac{21}{4} & \tfrac{7}{12} & -\tfrac{13}{6}
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_2\leftarrow \tfrac{1}{6}R_2\;}
\left[
\begin{array}{rrr|r}
12 & 9 & 1 & 10\\
0 & 1 & \tfrac{14}{9} & \tfrac{1}{18}\\
0 & \tfrac{21}{4} & \tfrac{7}{12} & -\tfrac{13}{6}
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_1\leftarrow R_1-9R_2,\; R_3\leftarrow R_3-\tfrac{21}{4}R_2\;}
\left[
\begin{array}{rrr|r}
12 & 0 & -13 & \tfrac{19}{2}\\
0 & 1 & \tfrac{14}{9} & \tfrac{1}{18}\\
0 & 0 & -\tfrac{91}{12} & -\tfrac{59}{24}
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_3\leftarrow -\tfrac{12}{91}R_3\;}
\left[
\begin{array}{rrr|r}
12 & 0 & -13 & \tfrac{19}{2}\\
0 & 1 & \tfrac{14}{9} & \tfrac{1}{18}\\
0 & 0 & 1 & \tfrac{59}{182}
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_2\leftarrow R_2-\tfrac{14}{9}R_3,\; R_1\leftarrow R_1+13R_3\;}
\left[
\begin{array}{rrr|r}
12 & 0 & 0 & \tfrac{96}{7}\\
0 & 1 & 0 & -\tfrac{35}{78}\\
0 & 0 & 1 & \tfrac{59}{182}
\end{array}
\right] \\[1.2em]
&\xrightarrow{\;R_1\leftarrow \tfrac{1}{12}R_1\;}
\left[
\begin{array}{rrr|r}
1 & 0 & 0 & \tfrac{8}{7}\\
0 & 1 & 0 & -\tfrac{35}{78}\\
0 & 0 & 1 & \tfrac{59}{182}
\end{array}
\right]
\end{aligned}
$$
