---
title: Review for exam 1
date: 2025-09-10
format:
  html:
    page-layout: article
    toc: true
  pdf:
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \pagenumbering{gobble}
---

Our first exam is next Wednesday, September 17! Here's our first draft of a review sheet.

## Problems

1. State the following definitions:

   a. Pivot position in a matrix. [Definition 1.4.1](https://understandinglinearalgebra.org/sec-pivots.html#sec-pivots-2-3){target=_blank}
   b. Linear Combination [Definition 2.1.9](https://understandinglinearalgebra.org/sec-vectors-lin-combs.html#sec-vectors-lin-combs-4-3){target=_blank}
   c. The span of a set of vectors [Definition 2.3.1](https://understandinglinearalgebra.org/sec-span.html#sec-span-3-4){target=_blank}
   d. Linear independence of a set of vectors [Definition 2.4.5](https://understandinglinearalgebra.org/sec-linear-dep.html#definition-linear-independence){target=_blank}
   e. Homogeneous system of equations [Top of section 2.4.3](https://understandinglinearalgebra.org/sec-linear-dep.html#sec-linear-dep-5){target=_blank}

2. In this problem, we're going to consider the types of solutions that *might* occur and typically *do* occur for linear systems of various sizes.

   a. Suppose that we have a linear system in 3 equations and 5 unknowns.
      i. *Generally*, how many solutions do we expect there to be?
      ii. Is it possible for there to be a *unique* solution?
      iii. Write down a possible RREF of an augmented matrix for such a system that has no solution.
   b. Suppose that we have a linear system in 5 equations and 3 unknowns.
      i. *Generally*, how many solutions do we expect there to be?
      ii. Is it possible for there to be a *unique* solution?
      iii. Write down a possible RREF of an augmented matrix for such a system that has infinitely many solutions.
   c. Suppose that we have a linear system in 4 equations and 4 unknowns.
      i. *Generally*, how many solutions do we expect there to be?
      ii. Write down a possible RREF of an augmented matrix for such a system that has exactly one solution.

3. Write down a componentwise proof of the fact that vector addition is associative. That is, if $\mathbf{u}$, $\mathbf{v}$, and $\mathbf{w}$ are vectors in $\mathbb{R}^n$, then 
$$(\mathbf{u} + \mathbf{v}) + \mathbf{w} = 
  \mathbf{u} + (\mathbf{v} + \mathbf{w}).$$  
  I guess you might try the same thing with commutativity.


<!-- Matrix generated by the following Sage code:
set_random_seed(1)
v1 = [randint(-2,3) for i in range(4)]
v2 = [randint(-2,3) for i in range(4)]
v3 = [randint(-2,3) for i in range(4)]
M = Matrix([v1,v2,v3,v3,v3])
M[2] = M[0] + M[1]
M[4] = 2*M[0] + M[3]
M = M.transpose()
latex(M)
-->
4. Consider the vectors that form the columns of the following matrix $M$:
$$
M = \left(\begin{array}{rrrrr}
0 & 1 & 1 & 2 & 2 \\
2 & -2 & 0 & -2 & 2 \\
-1 & 1 & 0 & 3 & 1 \\
1 & 3 & 4 & -1 & 1
\end{array}\right)
$$

   a. Without doing a single computation, explain why there's no way for these vectors to be linearly independent.
   b. Now, the RREF of $M$ is shown below. Based on that, find a linearly independent subset of the columns whose span is the same as the span of all the columns.

$$
\left(\begin{array}{rrrrr}
1 & 0 & 1 & 0 & 2 \\
0 & 1 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0 & 0
\end{array}\right)
$$

5. Let 
$$
\mathbf{x} = \left(\begin{array}{r}
1 \\
1 \\
0
\end{array}\right),
\: 
\mathbf{y} = \left(\begin{array}{r}
0 \\
-1 \\
1
\end{array}\right),
\: \text{and }
\mathbf{z} = \left(\begin{array}{r}
0 \\
0 \\
-1
\end{array}\right).
$$
Express the vector 
$$
\mathbf{u} = \left(\begin{array}{r}
2 \\
3 \\
-4
\end{array}\right)
$$
as a linear combination of $\mathbf{x}$, $\mathbf{y}$, and $\mathbf{z}$ or explain why there is no such linear combination.

6. Suppose that $A$ is a matrix of dimensions $5\times8$ and $B$ is a matrix of size $7\times5$. Then, what are the dimensions of the matrices 
   a. $AB$ and 
   b. $BA$?

7. Write down $2\times2$ matrices that perform the following actions. In some cases, you might want to express your answer as a product of matrices that perform simpler actions.

   a. Stretches by the factor 2 in the horizontal direction and by the factor 3 in the vertical.
   b. Stretches by the factor 2 in the horizontal direction by the factor 3 in the vertical, and also reflects across the $x$-axis.
   c. Projects on the line $y=x$.
   d. Reflects across a line through the origin that makes an angle of $17^{\circ}$ with the $x$ axis. 



::: {.content-visible when-format="html"}

## Your questions and solutions

If you'd like to ask a question about or reply to a question on this sheet, you can do so by pressing the "Reply on Discourse" button below.

```{ojs}
embedDiscourseMathTopic(39)
```

```{ojs}
import {embedDiscourseMathTopic} from '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.js';
```

:::
