---
title: Review for exam 2
date: 2025-10-22
format:
  html:
    page-layout: article
    toc: true
  pdf:
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \pagenumbering{gobble}
---




Our second exam is next Wednesday, October 29! Here's our review sheet.


## Mostly computational problems

Most of the problems on the exam will be like one of the following. This section might be a bit longer than what you'll see on the exam.

1. Write down careful and complete definitions of the following:

   a. Eigenvalue/Eigenvector pair for a matrix $A$ [Definition 1.4.1](https://understandinglinearalgebra.org/sec-eigen-intro.html#definition-eigenvectors){target=_blank}
   b. Characteristic polynomial of a matrix $A$ ([$\det(A-\lambda I)=0$](https://understandinglinearalgebra.org/sec-eigen-find.html#sec-eigen-find-3-4){target=_blank})
   c. Similarity of matrices [Definition 4.3.11](https://understandinglinearalgebra.org/sec-eigen-diag.html#sec-eigen-diag-5-4){target=_blank}
   d. Diagonalizable matrix [Definition 4.3.4](https://understandinglinearalgebra.org/sec-eigen-diag.html#sec-eigen-diag-3-8){target=_blank}
   e. ~~Nonsingular matrix~~

2. Write down three characterizations of *Invertible Matrix*.

3. Write down a $3\times3$ matrix that stretches by the factor 2 in the direction of the vector $\begin{bmatrix}2&1&1\end{bmatrix}^{\mathsf T}$

3. Suppose
	 $$
	 A = \left[
		\begin{array}{ccccc}
		 1 & 2 & 1 & 3 & 4 \\
		 2 & 4 & 1 & 4 & 5 \\
		 3 & 6 & 1 & 5 & 6 \\
		\end{array}
		\right]
	  $$
	 and that $A$ has reduced row echelon form
	 $$
		\left[
		\begin{array}{ccccc}
		 1 & 2 & 0 & 1 & 1 \\
		 0 & 0 & 1 & 2 & 3 \\
		 0 & 0 & 0 & 0 & 0 \\
		\end{array}
		\right].
	 $$
	 a. Find a basis for the null space of $A$.
	 b. Find a basis for the column space of $A$.
	 c. Find a basis for the row space of $A$.


4. In this problem, you're going to write down a couple of $3\times3$ matrices that perform specific geometric actions. In both cases, you should write your matrix as a factorization expressing its diagonal form, i.e. as $SDS^{-1}$.

   a. Write down a matrix that stretches by the factor 3 in the direction $\begin{bmatrix}1,1,1 \end{bmatrix}^{\mathsf T}$, that stretches by the factor 2 in the direction $\begin{bmatrix} 1,2,3 \end{bmatrix}^{\mathsf T}$, and that reflects in the direction $\begin{bmatrix} 3,-2,1 \end{bmatrix}^{\mathsf T}$.

   b. Write down a matrix that stretches by the factor 2 in the direction $\begin{bmatrix}1&2&3\end{bmatrix}^{\mathsf T}$ and induces pure rotation through the angle $\pi/4$ about the line with direction vector $\begin{bmatrix}1&1&1\end{bmatrix}^{\mathsf T}$.

5. Let $$A = \left[
            \begin{array}{cccc}
             -73 & 117 & -168 & 207 \\
             170 & -278 & 400 & -495 \\
             523 & -849 & 1220 & -1510 \\
             301 & -488 & 701 & -868 \\
            \end{array}
            \right].$$ Suppose I tell you that $A$ is similar to
   $$M = \left[
            \begin{array}{cccc}
             2 & 0 & 0 & 0 \\
             0 & -1 & 0 & 0 \\
             0 & 0 & 0 & -1 \\
             0 & 0 & 1 & 0 \\
            \end{array}
            \right].$$
   a. What are the eigenvalues of $A$?
   b. What can you deduce about the geometric action of $A$?
   c. What information about the geometric action of $A$ can you *not* deduce?

6. Let $$A = \left[\begin{matrix}1&-1\\6&6\end{matrix}\right].$$
   a. Diagonalize $A$.
   b. Evaluate $A^{10}\begin{bmatrix}1&1\end{bmatrix}^{\mathsf T}$

7. Use a determinant to write down an equation of the circle containing the points $(1,1)$, $(1,2)$, and $(-2,0)$. You may express your answer using an unexpanded determinant.


## More theoretical problems

There will probably be something a bit more theoretical on the exam. These sorts of questions typically require you to write down a definition or two and maybe a theorem and think about what that all tells you. If you're dealing with similarity of matrices, for example, you'll almost certainly need to play with the defining equation 
$$A = SBS^{-1}.$$
This section is certainly much longer than what you'll see on the exam.

1. Suppose that $A$ is similar to $B$ and that $\lambda$ is an
    eigenvalue of $A$ with corresponding eigenvector $\mathbf{x}$. Show
    that $\lambda$ is also an eigenvalue of $B$. What is the
    corresponding eigenvector of $B$?

2. Provide a counterexample to the statement that a square matrix is always similar to its inverse.

3. Suppose that $A$ is a square matrix. Explain why the constant term of
    the characteristic polynomial of $A$ is equal to the determinant of
    $A$.

4. Suppose that $A$ is similar to $B$ and that $n\in\mathbb N$. Show that $A^n$ is similar to $B^n$.

5. Suppose that $A$ is similar to $B$ and that $B$ is similar to $C$. Show that $A$ is similar to $C$.




::: {.content-visible when-format="html"}

## Your questions and solutions

If you'd like to ask a question about or reply to a question on this sheet, you can do so by pressing the "Reply on Discourse" button below.

```{ojs}
embedDiscourseMathTopic(45)
```

```{ojs}
import {embedDiscourseMathTopic} from '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.js';
```

:::
