---
title: Review for quiz 2
date: 2025-09-25
format:
  html:
    page-layout: article
    toc: true
  pdf:
    mainfont: "Times New Roman"
    include-in-header:
      text: |
        \pagenumbering{gobble}
---

We have our second quiz Wednesday, October 1st. Here's a first draft of a problem sheet for the quiz. It *might* be the final draft; I'm not sure.


## The problems

1. Write down the definition of each of the following:  

   a. Invertible Matrix [Definition 3.1.1](https://understandinglinearalgebra.org/sec-matrix-inverse.html#subsec-invertible-matrices-4)
   b. Subspace of $\mathbb R^n$ [Definition 3.5.1](https://understandinglinearalgebra.org/sec-subspaces.html#sec-subspaces-3-3)
   c. Basis  
      i. of $\mathbf R^n$ [Definition 3.2.3](https://understandinglinearalgebra.org/sec-bases.html#sec-bases-3-3)
      ii. of a subspace [Definition 3.5.4](https://understandinglinearalgebra.org/sec-subspaces.html#sec-subspaces-3-8)
   d. Column space of a matrix $A$ [Definition 3.5.6](https://understandinglinearalgebra.org/sec-subspaces.html#sec-subspaces-4-3)
   e. Null space of a matrix $A$ [Definition 3.5.10](https://understandinglinearalgebra.org/sec-subspaces.html#sec-subspaces-5-3)


2. For both of the matrices $A$ and $B$ below, find its inverse or explain briefly why you know the matrix is not invertible.
$$
A = \begin{bmatrix}
 1 & a & b \\
 0 & 1 & c \\
 0 & 0 & 1 \\
\end{bmatrix}
\: \: \: \: \:
B = \begin{bmatrix}
 1 & a & b \\
 0 & 0 & c \\
 0 & 0 & 1 \\
\end{bmatrix}
$$

3. For what values of $a$ is the following matrix invertible?

$$
A = \begin{bmatrix}
 a & -1 & 0 \\
 0 & -1 & -1 \\
 -1 & 0 & -1 \\
\end{bmatrix}
$$

4. The matrix $A$ together with its reduced row echelon form $R$ are 
$$
A = \begin{bmatrix}
 7 & -1 & 23 & -4 & -20 \\
 2 & 6 & -6 & 1 & 7 \\
 -7 & -1 & -19 & -1 & 3 \\
 0 & 8 & -16 & 1 & 11 \\
 -7 & -6 & -9 & 5 & 16 \\
\end{bmatrix}
\: \: \text{ and } \: \:
R = \begin{bmatrix}
 1 & 0 & 3 & 0 & -1 \\
 0 & 1 & -2 & 0 & 1 \\
 0 & 0 & 0 & 1 & 3 \\
 0 & 0 & 0 & 0 & 0 \\
 0 & 0 & 0 & 0 & 0 \\
\end{bmatrix}.
$$

   a. Is $A$ invertible?
   b. What is the dimension of the column space of $A$?
   c. What is the dimension of the row space of $A$?
   d. Find a basis for the column space of $A$.

::: {.content-visible when-format="html"}

## Your questions and solutions

If you'd like to ask a question about or reply to a question on this sheet, you can do so by pressing the "Reply on Discourse" button below.

```{ojs}
embedDiscourseMathTopic(40)
```

```{ojs}
import {embedDiscourseMathTopic} from '/components/EmbedDiscourseMathTopics/embedDiscourseMathTopic.js';
```

:::

