---
title: Massey ratings
format:
  html:
    css: style.css
    page-layout: article
    toc: true
    code-copy: true
    echo: true
---
 
This web page outlines a technique based in linear algebra to rate teams playing games in a common league based on the score differences that we see in the games. The basic idea is to perform a linear regression where the input consists of games and the output is the score differences.

This technique dates back to Ken Massey's 1997 senior honors thesis at Bluefield College. My understanding of the technique is based mostly on Chapter 2 of [Langville and Meyer's text on sport's ranking](https://press.princeton.edu/books/hardcover/9780691154220/whos-1).

## Code 

We'll describe the mathematics of Massey's algorithm and also shows how to implement it in Python. Each code block has a clipboard icon in the upper right that you can click on to copy the code. You should be able to run the code in a scientific Python environment.

### Imports


Let's go ahead and import the libraries that we'll need straight away:

```{python}
# Data manipulation
import pandas as pd

# Numerics
import numpy as np

# SciPy's linear system solver
from scipy.linalg import solve
```

## Description of the algorithm

Let's describe the algorithm and take a look at a relatively simple example

### The general problem

In general, we've got $m$ games played between $n$ teams. Let's suppose that in the $k^{\text{th}}$ game, team $i$ beat team $j$ by $y_k$ points. We'd like the teams ratings $r_i$ and $r_j$ to reflect this fact, i.e. we'd like
$$r_i - r_j = y_k.$$
To put it another way, we'd like our ratings of teams $i$ and $j$ to indicate the expected score difference between the teams, if they play again.

If $\vec{r}$ is the vector of ratings and $\vec{y}$ is the vector of point differences, then we can express this as the matrix equation
$$X\vec{r} = \vec{y},$$
where $X_{ki} = 1$, $X_{kj} = -1$, and all other entries are zero.

Now, there are generally many more games than teams so that the system we've written down is likely overdetermined. Nonetheless, we can attempt to find an approximate solution in the least squares sense and an efficient way to do so is to solve the so-called *normal equations* obtained by multiplying both sides by the transpose of $X$:
$$X^T X\vec{r} = X^T \vec{y},$$

The matrix $M = X^T X$ formed in this process is called the *Massey matrix* and has some interesting properties. Note that each entry in column $i$ of the matrix $X$ is either $1$ (if team $i$ won that game), $-1$ (if team $i$ lost that game), or zero (if team $i$ didn't play in that game).  As a result, $M_{ii}$ (which is obtained by computing the dot product of the $i^{\text{th}}$ column of $X$ with itself) denotes the number of games played by team $i$. Similarly, $M_{ij}$ is the opposite of the number of games played by teams $i$ and $j$. Thus, the sum of each row is zero. Put another way, the columns sum to the zero vector and are therefore linearly dependent. This implies that $M$ is singular so that the normal equations don't have a unique solution.


A way to get around this problem is to set all the elements in some row of $M$ equal to 1. This is conventionally done in the last row. We similarly replace the last element of
$$\vec{p} = X^T y$$
to zero. This implies the constraint that the sum of the ratings must be zero. Furthermore, the resulting system
$$M \vec{r} = \vec{p}$$
can be shown to have a unique solution.

### A simple working example

As a simple example, let's suppose that we have three teams labeled $A$, $B$, and $C$ and that each team plays the other teams twice each. We might visualize the collection of games via a labeled, directed graph like so:


```{python}
#| echo: false
#| classes: centered
import graphviz as gv 
dot = gv.Digraph()
dot.graph_attr.update({'rankdir': 'LR'})
dot.edge("A", "B", label="2")
dot.edge("A", "B", label="3")
dot.edge("B", "C", label="1")
dot.edge("C", "B", label="2")
dot.edge("A", "C", label="3")
dot.edge("C", "A", label="1")
dot
```

Note that a directed edge from team $i$ to team $j$ indicates that team $i$ defeated team $j$ in that game; the edge labels indicates the score differences. Given the directed graph shown above, how would you rank the teams?


To rank the teams the Massey way, we start with the general equation
$$X \vec{r} = \vec{y}$$
which takes the specific form

$$
\begin{pmatrix}1&-1&0\\1&-1&0\\0&1&-1\\0&-1&1\\1&0&-1\\-1&0&1\end{pmatrix}
\begin{pmatrix}r_0\\r_1\\r_2\end{pmatrix} =
\begin{pmatrix}3\\2\\1\\2\\3\\1\end{pmatrix}.
$$

If we multiply both sides by $X^T$ and modify the last rows according Massey's strategy, the equation becomes

$$
\begin{pmatrix}4&-2&-2\\-2&4&-2\\1&1&1\end{pmatrix}
\begin{pmatrix}r_0\\r_1\\r_2\end{pmatrix} =
\begin{pmatrix}7\\-6\\0\end{pmatrix}.
$$

The solution of this system is

$$
\begin{pmatrix}r_0\\r_1\\r_2\end{pmatrix} = \begin{pmatrix}7/6\\-1\\-1/6\end{pmatrix}.
$$

In particular, note that $r_1 < r_2 < r_0$, which is probably in accordance with the order you expected.

### The Massey equation

It's worth noting that the Massey equation
$$M\vec{r} = \vec{p}$$
can itself be written down and interpreted without reference to $X$ or $y$. As we've already noted, $M_{ii}$ denotes the number of games played by team $i$ and $M_{ij}$ is the opposite of the number of games played by teams $i$ and $j$. Similarly, the entries of $\vec{p}$ is the accumulated set of score differences for each team.

For example, if we expand the first term in the product $M\vec{r}$ and set that equal to the first term of $p$, we get
$$4r_0 - 2r_1 - 2r_2 = 7.$$
This indicates that team $0$ played four games, two against each other team, and that it outscored its opponents by a combined score of seven. If we solve for $r_0$, we get
$$r_0 = \frac{1}{2}r_1 + \frac{1}{2}r_2 + \frac{7}{2}.$$
In general, the rating of team $i$ is a combination of the ratings of the other teams together with the number of points that team $i$ outscored those other teams by.

## Implementation

Now, we'll implement the technique in code for both the simple example and a more realistic example.

### The simple example

Here's an implementation of the technique for the simple example described above in Python:

```{python}
X = np.array([
    [1, -1, 0],
    [1, -1, 0],
    [0, 1, -1],
    [0, -1, 1],
    [1, 0, -1],
    [-1, 0, 1]
  ])
M = X.transpose().dot(X)
M[-1] = np.ones(len(M))

y = np.array([[3], [2], [1], [2], [3], [1]])
y = np.array([3, 2, 1, 2, 3, 1])
y = X.transpose().dot(y)
y[-1]=0

solve(M,y)
```

This is exactly the `[7/6,-1,-1/6]` ratings that we mentioned above.

### Real College Football Data

Let's take a look at a somewhat bigger example. I happen to have a CSV file on my web space that has the scores of major conference college football games from 2017-2024 (excluding 2020), as well as this year's results for the B1G so far. We can grab that data and examine a sample like so:

```{python}
cfb_data = pd.read_csv('https://marksmath.org/data/cfb_games_by_conf_and_year.csv')
cfb_data.sample(10, random_state = 1) 
```

I'm going to grab the current results for this year from the B1G:

```{python} 
games = cfb_data[
  cfb_data.apply(lambda r: r.year == 2025 and r.conf == "B1G", axis=1)
].copy()
m = len(games)
print(m)
games.head(13)
```

So, there've been 56 games played so far and we can see the first 13 games. 

In order to apply Massey's technique, we're going to need to set up a matrix indexed by the teams. Thus, let's assign an index to each team.

```{python}
wteams = games.WTeamName
lteams = games.LTeamName
teams = pd.concat([wteams, lteams]).drop_duplicates().sort_values()
team_to_idx_dict = dict([(v,i) for i,v in enumerate(teams)])
n = len(teams)

games['WTeamIdx'] = games.WTeamName.apply(
  lambda t: team_to_idx_dict[t]
)
games['LTeamIdx'] = games.LTeamName.apply(
  lambda t: team_to_idx_dict[t]
)
games = games.reset_index().drop('index', axis=1)
games.tail(6)
```

OK, to implement Massey's algorithm, we'll initiate a matrix `X` and a vector `y`, and iterate through the games setting the values in `X` and `y` as we go. We use those to setup and solve the Massey equation.


```{python}
X = np.zeros([m,n])
y = np.zeros([m])
X.transpose().dot(y)

for i,r in games.iterrows():
    X[i, r.WTeamIdx] = 1
    X[i, r.LTeamIdx] = -1
    y[i] = r.WScore - r.LScore

M = X.transpose().dot(X)
M[-1,:] = 1
p =  X.transpose().dot(y)
p[-1] = 0

r = solve(M,p)
r
```

It's a bit hard to interpret just the vector `r`, so we'll match up the values in `r` with the teams and sort by rating.

```{python}
rank_teams = pd.DataFrame(teams)
rank_teams.columns = ['TeamName']
rank_teams['Rating'] = rank_teams.TeamName.apply(
  lambda t: r[team_to_idx_dict[t]]
)
rank_teams = rank_teams.sort_values('Rating', ascending=False).reset_index(drop=True)
rank_teams.index = rank_teams.index+1
rank_teams
```

Hey, not bad!

Now, if you happen to need that table in Markdown, you could generate it like so:

```{python}
print(rank_teams.to_markdown())
```


## Lab problem 

OK, now you're going to give it a try! Specifically, you should rank the teams for a specific year and conference as indicated in select menu below:

```{python}
#| echo: false
ojs_define(
  year_conf_pairs = cfb_data[['year', 'conf']].drop_duplicates().to_dict(orient='records')
)
```


```{ojs}
//| echo: false
viewof name = {
  const names = ["---","Audrey","ahajdare","bmartin3","Bryan","cflorest","Collin","Estelle_Morgan","Fin","gcarswel","Isabel","Jacob_Prime","jandrew4","jwiatrowski","Lauren","leibnizcaneatit","Leo","lexidooley","Lilia","mholden","SalMangum","The_One_True_Jacob","Zachary"];
  year_conf_pairs.forEach((o,i) => o['name'] = names[i]);
  return Inputs.select(year_conf_pairs, {format: o => o.name, label: "Discourse name:"})
}
```

```{ojs}
//| echo: false
{
  if(name.name != "---") {
    return md`You get to explore the ${name.year} ${name.conf}`
  }
  else {
    return md``
  }
}
```

Once you've got your year and conference, you can open [a Colab notebook](https://colab.research.google.com/drive/1gIHPXDkAhUKwq4sMJjmokfBqce92OhVC?usp=sharing#forceEdit=true&sandboxMode=true){target=_blank} and use the code on this page to rank your teams. Once you've ranked your teams, you can share your notebook with me.
