---
title: Math for Machine Learning
sidebar: false
css: styles.css
---

::: {.grid}
::::: {.g-col-12 .g-col-md-8}
Math 295  
Spring 2026  
with professor [Mark McClure](https://marksmath.org/)

## Handy links
  
- [Syllabus](syllabus.qmd)
- Schedule
  - [Outline](schedule/outline.qmd)
  - [Calendar](schedule/calendar.qmd)
- [MyOpenMath](https://myopenmath.com)
- [Discourse](https://discourse.marksmath.org/)
- [Colab](https://colab.research.google.com/)
- [The Math Lab!](https://math.unca.edu/learn/math-lab/)
- [Class presentations](./presentations)

## Notes and notebooks

- [Single parameter linear regression](./notes/single-parameter_linear_regression)
- [Using SageMath for linear algebra](./notes/sage)
- [Implementation of Gauss-Jordan Elimination](https://colab.research.google.com/drive/19EfrrYKpGC786Sdi-xHURAdPhU1YTkjl?usp=sharing#sandboxMode=true){target=_blank}
- [Some row reduction examples](./notes/some_row_reduction)
- [Matrix inverses](./notes/matrix_inverses)
- [Intro to Data](https://colab.research.google.com/drive/1aVdSbkPg_-SC88i04-G_jNCSRIeLYfTO?usp=sharing#sandboxMode=true){target=_blank}
- Linear Regression
  - [Theory and Practice](./notes/linear_regression_examples)
  - [Massey Ratings](./notes/massey_ratings)
- [Regression in practice](https://colab.research.google.com/drive/1HUpDEIWLMP-DhkWQ84_6LY3QYK9rL09Z?usp=sharing#sandboxMode=true){target=_blank}
- [Practical regression lab](https://colab.research.google.com/drive/1AD9QD6Ey89jSLZi8rjNmvyUKnpGwGBCm?usp=sharing#sandboxMode=true){target=_blank}

## Demos 
- [Digit recognizer](/visualization/data/digit_recognizer/)
- [Integration is hard!](/visualization/class/integration_is_hard)
- [Riemann sums](/visualization/class/RiemannSums)

## Handouts

- [Review for Exam I](./handouts/Exam1Review)
- [Review for Exam II](./handouts/Exam2Review)

:::::
::::: {.g-col-md-4 .d-none .d-md-block}
```{ojs}
// import {regression_animation} from './components/regression_animation.js'
// regression_animation();
data = [
  [12, 0.144239, 'agolriz'],
  [7, 0.1690946, "narito"],
  [16, 0.142155, "bmartin3"],
  [17, 0.14289, "prsteed"],
  [6, 0.16616, "Mel"],
  [19, 0.137243432, "Cornell"],
  [8, 0.154179958293, "qkupp"],
  [13, 0.15379, "lsavage1"],
  [8, 0.1499, "atobbe"],
  [8, 0.15877, "ncasteve"],
  [8.1, 0.15418, "edomanta"],
  [7.9, 0.154179958, "jgayfiel"],
  [18, 0.142443, "DanielD"],
  [13, 0.1442743482, "bjenkins"],
  [3, 0.196455, "mark"]
].map(function (a) {
  a.name = a[2];
  a.N = a[0];
  a.score = a[1];
  return a;
});
Plot.plot({
  width: 300,
  height: 250,
  x: { domain: [2, 20] },
  y: { domain: [0.135, 0.2] },
  marks: [
    Plot.dot(data, {
      x: "N",
      y: "score",
      tip: true,
      channels: { Name: "name", x: Math.round },
      fill: "black"
    }),
    Plot.linearRegressionY(data, {
      x: "N",
      y: "score",
      ci: 0,
      stroke: "red"
    }),
    Plot.ruleX([2]),
    Plot.ruleY([0.135])
  ]
})
```
:::::
:::
