---
title: Exponential functions, $e$, and slope
page-layout: article
echo: false
format:
    html:
        toc: true
        include-in-header:
            text: |
                <script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>
                <script>sagecell.makeSagecell({"inputLocation": ".sage"});</script>
---

## Introduction


[Wikipedia defines $e$](https://en.wikipedia.org/wiki/E_(mathematical_constant)#Definitions){target=_blank} in terms of a limit:
$$
e = \lim _{n\to \infty }\left(1+{\frac {1}{n}}\right)^{n}.
$$
As it turns out, this definition makes $e^x$ as simple to differentiate as possible!

## Exponential functions

An exponential function is a function of the form $f(x) = b^x$. The number $b$ is called the *base* and can be anything larger than zero.

It's pretty easy to compute the value of an exponential function at an integer, since it's just
$$b^n=\overbrace{b\times b\times\cdots\times b}^{n\text{ times}}.$$

As a result, it's pretty easy to graph an exponential function: just plot some values at a few integers and connect the dots!

```{ojs}
viewof fs = Inputs.checkbox(
    ["2^x", "e^x", "3^x"], 
    {format: d => tex`${d}`, label: "Plot:"}
);
```
```{ojs}
plots_with_dots(fs, state);
```
```{ojs}
state = [];
```

Note that the larger the base, the steeper the function:

```{ojs}
viewof b = Inputs.range([0.25,4], {value: 2, step: 0.001, label: "b:"})
```
```{ojs}
simple_plot(b)
```


## The derivative

We measure steepness, of course, with the derivative. When trying to really understand the derivative of a new function, we generally apply the difference quotient. Here's how:

$$\begin{aligned}
\frac{d}{dx} b^x &= \lim_{h\to0} \frac{b^{x+h}-b^x}{h} = \lim_{h\to0} \frac{b^xb^h-b^x}{h} \\
&= b^x \lim_{h\to0}\frac{b^h-1}{h} = c_b \, b^x. 
\end{aligned}$$

The value of that limit $\lim_{h\to0}(b^h-1)/h$ is presumably *some* number, which I've chosen to denote with a $c_b$. Thus, this computation suggests that the derivative of any exponential function is simply a constant times that exponential function you started with.

The limit that this leads to
$$
\lim_{h\to0}\frac{b^h-1}{h}
$$ 
is not quite as elementary as those limits that arise when dealing with algebraic functions like polynomials. There's no evident way to cancel the $h$ in the denominator. 

We're going to tackle this from a couple different directions:

- Graphically and
- Numerically

### The geometric look

The value of $c_b$ has a simple geometric interpretation. If $f(x) = b^x$, then
$$
f'(x) = c_bb^x \text{ so that } f'(0) = c_b.
$$
Thus, $c_b$ represents the slope of $y=b^x$ as the graph crosses the $y$-axis.

Let's take a closer look at the graphs of $2^x$, $3^x$, and $e^x$:

```{ojs}
viewof parameters = Inputs.form([
  Inputs.toggle({label:"Base two:", value: true}),
  Inputs.toggle({label:"Base three:", value: false}),
  Inputs.toggle({label:"Base e:", value: false})
]);
viewof h = Inputs.range([-2,2], {value: 1, step: 0.01, label: 'h:'});
```

```{ojs}
html`
<div style="position: relative; height: 400px">
  <div style="position: absolute; top:110px; left: 90px">
    ${parameters[0]
      ? tex`m_2 \approx ${d3.format("0.3f")((2 ** h - 1) / h)}`
      : ""}
  </div>
  <div style="position: absolute; top:135px; left: 90px">
    ${parameters[1]
      ? tex`m_3 \approx ${d3.format("0.3f")((3 ** h - 1) / h)}`
      : ""}
  </div>
  <div style="position: absolute; top:160px; left: 90px">
    ${parameters[2]
      ? tex`m_e \approx ${d3.format("0.3f")((Math.exp(h) - 1) / h)}`
      : ""}
  </div>
  <div style="position: absolute; top:0; left:0">
    ${plots_with_slopes(parameters, h)}
  </div>
</div>`
```

Note that $2^x$ crosses the $y$-axis with slope less than one; $3^x$ crosses the $y$-axis with slope just a little more than one. It stands to reason that there should be a number between the two where the slope is *exactly* one. The number $e$ is, by definition, exactly that number!

### The numeric look

Let's take a closer look at this limit numerically. To this end, @tbl-funvalues lists values of 
$$(2^h-1)/h \text{ and }(3^h-1)/h$$ 
near $h=0$.
 
```{python}
#| label: tbl-funvalues
#| tbl-cap: Values of $(2^h-1)/h$ and $(3^h-1)/h$ near $h=0$

from IPython.display import Markdown

h_vals = [10**(-n) for n in range(1,7)]
def f2(h):
    return (2**h - 1)/h
def f3(h):
    return (3**h - 1)/h

header = "   |   | " + " | ".join(" " for h in h_vals) + " |"

# separator row: one "---" per column
sep = "|" + "---|" * (len(h_vals) + 1)

# data rows: first cell is math header
row_h  = "| $h$   | " + " | ".join(f"{h:.6f}" for h in h_vals) + " |"
row_2h = "| $(2^h-1)/h$ | " + " | ".join(f"{f2(h):.6f}" for h in h_vals) + " |  "
row_3h = "| $(3^h-1)/h$ | " + " | ".join(f"{f3(h):.6f}" for h in h_vals) + " |  "

md_table = "\n   ".join([header, sep, row_h, row_2h, row_3h]) + "  "

indented_table = "\n".join("    " + line for line in md_table.splitlines())

Markdown(md_table)
```

The table indicates that 
$$
\lim_{h\to0} \frac{2^h-1}{h} \approx 0.6931 \text{ and } 
\lim_{h\to0} \frac{3^h-1}{h} \approx 1.0986.
$$
This suggests that there must be some value of $b$ between $2$ and $3$ so that the limit 
$$
\lim_{h\to0}\frac{b^h-1}{h} \text{ is exactly } 1.
$$ 
We denote this value of $b$ with the letter $e$. That is, the number $e$ is chosen, by definition, to be the unique number such that 
$$
\lim_{h\to0}\frac{e^h-1}{h} = 1. 
$$
The great thing about this from the perspective of calculus is that it explains the simpler formula for the derivative of the exponential function, namely
$$
\frac{d}{dx} e^x = e^x.
$$
Thus $f(x) = e^x$ is the exponential function whose derivative is as simple as possible.

### The limit definition

So, how does this approach to $e$ as the natural exponential base relate to Wikipedia's claim that 
$$
e = \lim _{n\to \infty }\left(1+{\frac {1}{n}}\right)^{n}?
$$
Well, if 
$$
\lim_{h\to0}\frac{e^h-1}{h} = 1,
$$
then for small values of $h$ we must have
$$
\frac{e^h-1}{h} \approx 1. 
$$
Solving for $e$, we get 
$$
e \approx (1+h)^{1/h}
$$
or, maybe
$$
e = \lim_{h\to0} (1+h)^{1/h}.
$$
The advantage here is that it makes it much easier to compute estimates for the numerical value of $e$; simply plug values of $h$ that are close to zero into $(1+h)^{1/h}$. The common definition stated by Wikipedia is simply a sequential version of this obtained with the identification $n=1/h$. The limit then becomes
$$
e = \lim_{n\to\infty} \left(1+\frac{1}{n}\right)^{n}.
$$
We can then approximate $e$ by plugging in large values of $n$ into $(1+1/n)^n$.

```{python}
#| label: tbl-evalues
#| tbl-cap: Values of $(1+1/n)^n$ for large $n$

from IPython.display import Markdown
n_vals = [10**(n) for n in range(1,7)]
def fe(n):
    return (1+1/n)**n

header = "   |   | " + " | ".join(" " for n in n_vals) + " |"

# separator row: one "---" per column
sep = "|" + "---|" * (len(n_vals) + 1)

# data rows: first cell is math header
row_n  = "| $n$   | " + " | ".join(f"{n}" for n in n_vals) + " |"
row_e = "| $(1+1/n)^n$ | " + " | ".join(f"{fe(n):.6f}" for n in n_vals) + " |  "

md_table = "\n   ".join([header, sep, row_n, row_e]) + "  "

indented_table = "\n".join("    " + line for line in md_table.splitlines())

Markdown(md_table)
```

It looks like $e\approx 2.718$. A more precise approximation is 
$$
e \approx 2.7182818284590452353602874714.
$$

## Building a limit table 

Here's a little code (in a language called SageMath) that allows you to define your base `b` and then prints a table of values of $h$ vs $(b^h - 1)/h$ for various values of $h$:

<div class="sage">
  <script type="text/x-sage">
b = 3
table = f"|h|({b}^h-1)/h|\n|:---:|:---:|\n"
for n in range(1,7):
    h = 10.0^(-n)
    df = (b^h - 1)/h
    table = table + f"|{h:.6f}|{df}|\n"
print(table)
    </script>
</div>

That's live code so that you can execute it or even edit it and *then* execute it. Could prove handy for a homework problem!


```{ojs}
import {plots_with_dots, plots_with_slopes, simple_plot} from './plots.js';
```